services:
  - type: web
    name: igbo-annotation-tool
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
    plan: free
    autoDeploy: true
    # Explicitly specify port binding
    port: 10000
    # Limit memory usage
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
    initialDeployHook:
      shellCommand: echo "Starting deployment"
